name: 'Deployer Validation'
description: 'Verifies that repo is deployable using public deployers'
author: '@mshanemc (Shane McLaughlin)'
inputs:
  deployer-url:
    description: 'base url for the deployer (not including path like /launch)'
    default: 'https://hosted-scratch.herokuapp.com'
runs:
  using: 'node12'
  main: 'dist/index.js'
